disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - todo
  - nesting
  - operator_whitespace
  - large_tuple
  - closure_parameter_position
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  - Sources/RealHTTP
excluded: # paths to ignore during linting. overridden by `included`.

identifier_name:
  excluded:
    - bg
    - fg
    - id
    - os
    - SQLITE_TRANSIENT
    - SQLITE_STATIC
    
type_body_length:
  warning: 260
  error: 260

function_body_length:
  warning: 60
  error: 60

line_length:
  warning: 150
  error: 150
  ignores_comments: true

file_length:
  warning: 500
  error: 500
  ignore_comment_only_lines: true
